name: IIN
version: '1.0'
main: zeru.iin.IIN
api-version: '1.21'
authors: [Zeru]
description: Plugin para IIN

commands:
  played:
    description: Muestra el tiempo jugado
    usage: /played

  mined:
    description: Muestra los bloques minados
    usage: /mined

  customitem:
    description: Da el item custom a eleccion
    usage: /customitem
    permission: iin.customitem

  maintenance:
    description: Activa/Desactiva el mantenimiento
    permission: iin.maintenance